server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security?useSSL=false
    username: root
    password: Asdf@1999

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  spring:
    main:
      allow-bean-definition-overriding: true